api_user_login_check:
    path: /auth
    defaults: { _controller: TickitUserBundle:Security:check }
    methods: [POST]

api_user_fetch:
    path: /fetch/{id}
    defaults: { _controller: tickit_user.controller.api:fetchAction, id: null }
    methods: [GET]
    requirements:
        id: \d+
    options:
        expose: true

api_user_list:
    path: /list/{page}
    defaults: { _controller: tickit_user.controller.api:listAction, page: 1 }
    methods: [GET]
    requirements:
        page: \d+
    options:
        expose: true
