api_user_login_check:
    pattern: /auth
    defaults: { _controller: TickitUserBundle:Security:check }
    requirements:
        _method: POST

api_user_fetch:
    pattern: /fetch/{id}
    defaults: { _controller: tickit_user.controller.api:fetchAction, id: null }
    requirements:
        id: \d+
        _method: GET
    options:
        expose: true

api_user_list:
    pattern: /list/{page}
    defaults: { _controller: tickit_user.controller.api:listAction, page: 1 }
    requirements:
        page: \d+
        _method: GET
    options:
        expose: true
