fos_user_security_login:
    path: /login
    defaults: { _controller: tickit.controller.default:defaultAction }
    methods: [GET]
    options:
        expose: true

user_index:
    path: /users/{page}
    defaults: { _controller: tickit.controller.default:defaultAction, page: 1 }
    methods: [GET]
    requirements:
        page: \d+
    options:
        expose: true

user_create_view:
    path: /users/create
    defaults: { _controller: tickit.controller.default:defaultAction }
    methods: [GET]
    options:
        expose: true

user_edit_view:
    path: /users/edit/{id}
    defaults: { _controller: tickit.controller.default:defaultAction }
    methods: [GET]
    requirements:
        id: \d+
    options:
        expose: true
