fos_user_security_login:
    pattern: /login
    defaults: { _controller: tickit.controller.default:defaultAction }
    requirements:
        _method: GET
    options:
        expose: true

user_index:
    pattern: /users/{page}
    defaults: { _controller: tickit.controller.default:defaultAction, page: 1 }
    requirements:
        page: \d+
        _method: GET
    options:
        expose: true

user_create_view:
    pattern: /users/create
    defaults: { _controller: tickit.controller.default:defaultAction }
    requirements:
        _method: GET
    options:
        expose: true

user_edit_view:
    pattern: /users/edit/{id}
    defaults: { _controller: tickit.controller.default:defaultAction }
    requirements:
        id: \d+
        _method: GET
    options:
        expose: true
