picker_user_find:
    path: /find/{term}
    defaults: { _controller: tickit_user.controller.picker:findAction }
    methods: [GET]
    requirements:
        term: '[a-zA-Z]{3,}'
    options:
        expose: true
