user_login_form:
    path: /login-form
    defaults: { _controller: TickitUserBundle:Security:login }
    methods: [GET]

user_create_form:
    path: /create
    defaults: { _controller: tickit_user.controller.template:createFormAction }
    methods: [GET]
    options:
        expose: true

user_edit_form:
    path: /edit/{id}
    defaults: { _controller: tickit_user.controller.template:editFormAction }
    methods: [GET]
    requirements:
        id: \d+
    options:
        expose: true

user_filter_form:
    path: /filter-form
    defaults: { _controller: tickit_user.controller.template:filterFormAction }
    methods: [GET]
    options:
        expose: true
