api:
    resource: "@TickitUserBundle/Resources/config/routing/api.yml"
    prefix: /api/users

templates:
    resource: "@TickitUserBundle/Resources/config/routing/templates.yml"
    prefix: /templates/users

cosmetic:
    resource: "@TickitUserBundle/Resources/config/routing/cosmetic.yml"

picker:
    resource: "@TickitUserBundle/Resources/config/routing/pickers.yml"
    prefix: /picker/users

##########################################

user_create:
    path: /users/create
    defaults: { _controller: tickit_user.controller.user:createAction }
    methods: [POST]

user_edit:
    path: /users/edit/{id}
    defaults: { _controller: tickit_user.controller.user:editAction }
    methods: [POST]
    requirements:
        id: \d+
        _method: post

user_delete:
    path: /users/delete/{id}
    defaults: { _controller: tickit_user.controller.user:deleteAction }
    methods: [DELETE]
    requirements:
        id: \d+
    options:
        expose: true

fos_user_profile:
  resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
  prefix: /profile

fos_user_register:
  resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
  prefix: /register

fos_user_resetting:
  resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
  prefix: /resetting

fos_user_change_password:
  resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
  prefix: /profile

fos_user_security_logout:
    path: /logout
    defaults: { _controller: FOSUserBundle:Security:logout }