language: php
php:
  - 5.4
  - 5.5

addons:
  sauce_connect:
    username: "jameshalsall"
    access_key: "fcf4c1eb-3fcf-4179-b683-0f3ef0a1201f"
  hosts:
    - tickit.local

before_script:

  # prepare config files and get vendors#
  - php app/Resources/data/travis-build.php

  - curl -s http://getcomposer.org/installer | php
  - php composer.phar --dev install

  # set up test environment #
  - php app/console tickit:tests:setup --env test
  - php app/console assets:install --symlink

script:
  - ./bin/phpcs ./src/Tickit --standard=PSR2 --warning-severity=notice --extensions=php
  - npm install bower
  - bower install
  - php app/console cache:warmup --env test
  - phpunit -c app/phpunit.xml --coverage-clover=build/logs/clover.xml
#  - bin/behat --profile saucelabs_win7_firefox

after_script:
  - php bin/coveralls -vvv

notifications:
  email:
    - james.t.halsall@googlemail.com
    - mw870618@gmail.com
    - sparky@sparky-san.com

branches:
  only:
    - master
    - development