language: php
php:
  - 5.4
  - 5.5

before_script:

  # prepare config files and get vendors#
  - php app/Resources/data/travis-build.php

  - curl -s http://getcomposer.org/installer | php
  - php composer.phar --dev install

  # set up test environment #
  - php app/console tickit:tests:setup --env test

script:
  - ./bin/phpcs ./src/Tickit --standard=PSR2 --warning-severity=notice --extensions=php
  - npm install bower
  - bower install
  - phpunit -c app/phpunit.xml --coverage-clover=build/logs/clover.xml

after_script:
  - php bin/coveralls -vvv

notifications:
  email:
    - james.t.halsall@googlemail.com
    - mw870618@gmail.com
    - sparky@sparky-san.com

branches:
  only:
    - master
    - development