issue_index:
    path: /issues/{page}
    defaults: { _controller: tickit.controller.default:defaultAction, page: 1 }
    methods: [GET]
    requirements:
        page: \d+
    options:
        expose: true
