api_user_login_check:
    pattern: /auth
    defaults: { _controller: TickitUserBundle:Security:check }
    requirements:
        _method: POST

api_user_fetch:
    pattern: /fetch/{id}
    defaults: { _controller: TickitUserBundle:Api:fetch, id: null }
    requirements:
        id: \d+
        _method: GET
    options:
        expose: true

api_user_list:
    pattern: /list/{page}
    defaults: { _controller: TickitUserBundle:Api:list, page: 1 }
    requirements:
        page: \d+
        _method: GET
    options:
        expose: true

api_group_list:
    pattern: /groups/list/{page}
    defaults: { _controller: TickitUserBundle:Api:listGroups, page: 1 }
    requirements:
        page: \d+
        _method: GET
    options:
        expose: true
