user_login_form:
    pattern: /login-form
    defaults: { _controller: TickitUserBundle:Security:login }
    requirements:
        _method: GET

user_create_form:
    pattern: /create
    defaults: { _controller: tickit_user.controller.template:createUserFormAction }
    options:
        expose: true
    requirements:
        _method: GET

user_edit_form:
    pattern: /edit/{id}
    defaults: { _controller: tickit_user.controller.template:editUserFormAction }
    requirements:
        id: \d+
        _method: GET
    options:
        expose: true
