default:
    paths:
        features: features
    context:
        parameters:
            javascript_session: selenium2
    extensions:
        Behat\MinkExtension\Extension:
            base_url: "http://tickit.local/app_test.php"
            default_session: symfony2
            browser_name: firefox
            selenium2: ~
        Behat\Symfony2Extension\Extension:
            mink_driver: true
            kernel:
                env: test
                debug: true
