default:
    paths:
        features: features
    context:
        parameters:
            javascript_session: selenium2
            hostname: %hostname%
    extensions:
        Behat\MinkExtension\Extension:
            default_session: symfony2
            browser_name: firefox
            selenium2: ~
        Behat\Symfony2Extension\Extension:
            mink_driver: true
            kernel:
                env: test
                debug: true
