imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: requirejs.yml }

framework:
    #esi:             ~
    translator:      ~
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    session:
        name: sessionId

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - 'TickitUserBundle:Form:tickit_roles_widget.html.twig'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: true
    filters:
        cssrewrite: ~
        less:
            node: %node_bin%
            node_paths: [%kernel.root_dir%/Resources/node_modules]

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        mappings:
            TickitClientBundle:
                prefix: Tickit\Component\Model\Client
            TickitPreferenceBundle:
                prefix: Tickit\Component\Preference\Model
            TickitProjectBundle:
                prefix: Tickit\Component\Model\Project
            TickitNotificationBundle:
                prefix: Tickit\Component\Notification\Model
            TickitUserBundle:
                prefix: Tickit\Component\Model\User
            TickitTicketBundle:
                prefix: Tickit\Component\Model\Ticket

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }


# FOSUserBundle Configuration
fos_user:
    db_driver:     orm
    firewall_name: main
    user_class:   Tickit\Component\Model\User\User
    registration:
        form:
            type: tickit_user_registration
    profile:
        form:
            type: tickit_user_profile
    service:
        user_manager: tickit_user.manager

fos_js_routing:
    routes_to_expose: [ fos_user_security_logout ]

# StofDoctrineExtensions Configuration
stof_doctrine_extensions:
  orm:
    default:
      timestampable: true
      softdeleteable: true

tickit_user:
    avatar:
        adapter_class: Tickit\Component\Avatar\Adapter\GravatarAdapter

tickit_notification:
    api_message_limit: 25
