imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: require-js.yml }

framework:
    #esi:             ~
    translator:      ~
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    session:
        name: sessionId

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - 'TickitPermissionBundle:Form:fields.html.twig'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        less:
            node: %node_bin%
            node_paths: [%node_lib%]
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }


# FOSUserBundle Configuration
fos_user:
    db_driver:     orm
    firewall_name: main
    user_class:   Tickit\UserBundle\Entity\User
    registration:
        form:
            type: tickit_user_registration
    profile:
        form:
            type: tickit_user_profile
    group:
        group_class: Tickit\UserBundle\Entity\Group
    service:
        user_manager: tickit_user.manager

# StofDoctrineExtensions Configuration
stof_doctrine_extensions:
  orm:
    default:
      timestampable: true
      softdeleteable: true

# TickitCacheBundle configuration
tickit_cache:
    default_namespace: tickit
    types:
        file:
            auto_serialize: true
        memcached:
            persistence_id: tickit
            servers:
                main:
                    host: localhost
                    name: main
                    weight: 90
                    retry_time: 5
                    enabled: true

tickit_user:
    avatar:
        adapter_class: Tickit\UserBundle\Avatar\Adapter\GravatarAdapter

tickit_notification:
    api_message_limit: 25