imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    router:   { resource: "%kernel.root_dir%/config/routing_test.yml" }
    session:
        storage_id: session.storage.mock_file
    profiler:
        enabled: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        user:     %database_user%
        dbname:   %database_name_test%
        host:     %database_host%
        port:     %database_port%
        password: %database_password%
        charset:  UTF8

# Test specific firewall
security:
    firewalls:
        main:
            pattern: ^/
            http_basic:
                realm: "Secured Test"
                provider: tickit_userbundle
