imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    router:   { resource: "%kernel.root_dir%/config/routing_test.yml" }
    session:
        storage_id: session.storage.mock_file

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        user:     %database_user%
        dbname:   %database_name%_tests
        host:     %database_host%
        port:     %database_port%
        password: %database_password%
        charset:  UTF8

# Test specific firewall
security:
    providers:
        fos_userbundle:
            id: tickit_user.user_provider
    firewalls:
        main:
            pattern: ^/
            http_basic:
                realm: "Secured Test"
                provider: fos_userbundle

#TickitCacheBundle configuration
tickit_cache:
    default_namespace: "tickit.test"
    types:
        file:
            auto_serialize: true
            default_path: "%kernel.cache_dir%/tickit_cache"
        memcached:
            persistence_id: tickit
            servers:
                main:
                    host: localhost
                    name: main
                    weight: 100
                    retry_time: 5
                    enabled: true
                alternate:
                    name: alternate
                    host: localhost
                    weight: 0
                    port: 11211
                    retry_time: 10
                    enabled: true