# Our test environment is only used for web acceptance testing.
# The unit tests in Tickit do not use the kernel or the container,
# so we can safely assume that all configuration in this file is
# for acceptance testing via behat/mink. For this reason we want to
# simulate the production environment in as many ways as possible
# whilst still retaining "test safety" (e.g. not dispatching real
# emails)

imports:
    - { resource: config_prod.yml }
    - { resource: requirejs_prod.yml }

framework:
    test: ~
    router:   { resource: "%kernel.root_dir%/config/routing_test.yml" }
    profiler:
        enabled: false
    session:
        storage_id: session.storage.native
        name: sessionId

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        user:     %database_user%
        dbname:   %database_name_test%
        host:     %database_host%
        port:     %database_port%
        password: %database_password%
        charset:  UTF8

assetic:
    use_controller: true
