hearsay_require_js:
    require_js_src: http://cdnjs.cloudflare.com/ajax/libs/require.js/2.1.8/require.min.js
    optimizer:
        path: %kernel.root_dir%/Resources/node_modules/requirejs/bin/r.js
        hide_unoptimized_assets: false
        options:
            findNestedDependencies: true
    base_dir: %kernel.root_dir%/Resources/public/js
    paths:
        jquery: %kernel.root_dir%/Resources/public/js/vendor/jquery/jquery
        text: %kernel.root_dir%/Resources/public/js/vendor/requirejs-text/text
        backbone: %kernel.root_dir%/Resources/public/js/vendor/backbone/backbone
        marionette: %kernel.root_dir%/Resources/public/js/vendor/backbone.marionette/lib/backbone.marionette
        underscore: %kernel.root_dir%/Resources/public/js/vendor/underscore/underscore
        cookie: %kernel.root_dir%/Resources/public/js/vendor/jquery.cookie/jquery.cookie
        sidr: %kernel.root_dir%/Resources/public/js/vendor/sidr/jquery.sidr.min
        noty: %kernel.root_dir%/Resources/public/js/vendor/noty/js/noty
        modules/app: '@TickitCoreBundle/Resources/public/js/App'
        modules/core: '@TickitCoreBundle/Resources/public/js/App.Core'
        modules/router: '@TickitCoreBundle/Resources/public/js/App.Router'
        modules/template: '@TickitCoreBundle/Resources/public/js/App.Template'
        modules/request: '@TickitCoreBundle/Resources/public/js/App.Request'
        modules/login: '@TickitUserBundle/Resources/public/js/App.Login'
        modules/dashboard: '@TickitDashboardBundle/Resources/public/js/App.Dashboard'
        modules/navigation: '@TickitNavigationBundle/Resources/public/js/App.Navigation'
        modules/user: '@TickitUserBundle/Resources/public/js/App.User'
        modules/project: '@TickitProjectBundle/Resources/public/js/App.Project'
        modules/notification: "@TickitNotificationBundle/Resources/public/js/App.Notification"
        modules/client: "@TickitClientBundle/Resources/public/js/App.Client"
        modules/messenger: "@TickitNotificationBundle/Resources/public/js/App.Messenger"
        core: '@TickitCoreBundle/Resources/public'
        navigation: "@TickitNavigationBundle/Resources/public"
        project: "@TickitProjectBundle/Resources/public"
        user: "@TickitUserBundle/Resources/public"
        client: "@TickitClientBundle/Resources/public"
        dashboard: "@TickitDashboardBundle/Resources/public"
        notification: "@TickitNotificationBundle/Resources/public"
        filter: "@TickitFilterBundle/Resources/public"
    shim:
        -
            name: jquery
            exports: '$'
        -
            name: underscore
            exports: '_'
        -
            name: backbone
            deps: [jquery, underscore]
            exports: 'Backbone'
        -
            name: marionette
            deps: [backbone]
            exports: 'Backbone.Marionette'
        -
            name: jqueryui
            deps: [jquery]
        -
            name: cookie
            deps: [jquery]
        -
            name: sidr
            deps: [jquery]
        -
            name: noty
            deps: [jquery]
