jms_security_extra:
    secure_all_services: false
    expressions: true

security:
     providers:
         fos_userbundle:
             id: tickit_user.user_provider

     encoders:
         "FOS\UserBundle\Model\UserInterface":
             algorithm: sha512
             encode_as_base64: true
             iterations: 5

     firewalls:
         main:
             pattern: ^/
             form_login:
                 provider: fos_userbundle
                 csrf_provider: form.csrf_provider
                 default_target_path: /dashboard
                 always_use_default_target_path: true
             logout:       true
             anonymous:    true

     access_control:
         - { path: ^/css|js|images, role: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/_profiler, role: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/_wdt, role: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/, role: ROLE_USER }

     role_hierarchy:
         ROLE_ADMIN:       ROLE_USER
         ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
