api_project_list:
    path: /list/{page}
    defaults: { _controller: tickit_project.controller.api:listAction, page: 1 }
    methods: [GET]
    requirements:
        page: ^[1-9][0-9]*$
    options:
        expose: true

api_project_attribute_list:
    path: /attributes/list/{page}
    defaults: { _controller: tickit_project.controller.api:attributesListAction, page: 1 }
    methods: [GET]
    requirements:
        page: \d+
    options:
        expose: true
