project_index:
    path: /projects/{page}
    defaults: { _controller: tickit.controller.default:defaultAction, page: 1 }
    methods: [GET]
    requirements:
        page: \d+
    options:
        expose: true

project_create_view:
    path: /projects/create
    defaults: { _controller: tickit.controller.default:defaultAction }
    methods: [GET]
    options:
        expose: true

project_edit_view:
    path: /projects/edit/{id}
    defaults: { _controller: tickit.controller.default:defaultAction }
    methods: [GET]
    requirements:
        id: \d+
    options:
        expose: true

project_attribute_index:
    path: /attributes/{page}
    defaults: { _controller: tickit.controller.default:defaultAction, page: 1 }
    methods: [GET]
    requirements:
        page: \d+
    options:
        expose: true
