project_create_form:
    path: /create
    defaults: { _controller: tickit_project.controller.template:createProjectFormAction }
    methods: [GET]
    options:
        expose: true

project_edit_form:
    path: /edit/{id}
    defaults: { _controller: tickit_project.controller.template:editProjectFormAction }
    methods: [GET]
    requirements:
        id: \d+
    options:
        expose: true

project_attribute_create_form:
    path: /attributes/create/{type}
    defaults: { _controller: tickit_project.controller.template:createProjectAttributeFormAction }
    methods: [GET]
    requirements:
        type: \w{6,7}
    options:
        expose: true

project_attribute_edit_form:
    path: /attributes/edit/{id}
    defaults: { _controller: tickit_project.controller.temmplate:editProjectAttributeFormAction }
    methods: [GET]
    requirements:
        id: \d+
    options:
        expose: true

project_filter_form:
    path: /filter-form
    defaults: { _controller: tickit_project.controller.template:filterFormAction }
    methods: [GET]
    options:
        expose: true
