cosmetic:
    resource: "@TickitClientBundle/Resources/config/routing/cosmetic.yml"

api:
    resource: "@TickitClientBundle/Resources/config/routing/api.yml"
    prefix: /api/clients

templates:
    resource: "@TickitClientBundle/Resources/config/routing/templates.yml"
    prefix: /templates/clients

client_create:
    path: /clients/create
    defaults: { _controller: tickit_client.controller.client:createAction }
    methods: [POST]

client_edit:
    path: /clients/edit/{id}
    defaults: { _controller: tickit_client.controller.client:editAction }
    methods: [POST]
    requirements:
        id: \d+

client_delete:
    path: /clients/delete/{id}
    defaults: { _controller: tickit_client.controller.client:deleteAction }
    requirements:
        id: \d+
    options:
        expose: true