client_index:
    path: /clients/{page}
    defaults: { _controller: tickit.controller.default:defaultAction, page: 1 }
    methods: [GET]
    requirements:
        page: \d+
    options:
        expose: true

client_create_view:
    path: /clients/create
    defaults: { _controller: tickit.controller.default:defaultAction }
    methods: [GET]
    options:
        expose: true

client_edit_view:
    path: /clients/edit/{id}
    defaults: { _controller: tickit.controller.default:defaultAction }
    methods: [GET]
    requirements:
        id: \d+
    options:
        expose: true
