client_create_form:
    pattern: /create
    defaults: { _controller: tickit_client.controller.template:createClientFormAction }
    options:
        expose: true

client_edit_form:
    pattern: /edit/{id}
    defaults: { _controller: tickit_client.controller.template:editClientFormAction }
    requirements:
        id: \d+
    options:
        expose: true

client_filter_form:
    pattern: /filter-form
    defaults: { _controller: tickit_client.controller.template:filterFormAction }
    requirements:
        _method: GET
    options:
        expose: true
