client_create_form:
    path: /create
    defaults: { _controller: tickit_client.controller.template:createClientFormAction }
    methods: [GET]
    options:
        expose: true

client_edit_form:
    path: /edit/{id}
    defaults: { _controller: tickit_client.controller.template:editClientFormAction }
    methods: [GET]
    requirements:
        id: \d+
    options:
        expose: true

client_filter_form:
    path: /filter-form
    defaults: { _controller: tickit_client.controller.template:filterFormAction }
    methods: [GET]
    options:
        expose: true
