api:
    resource: "@TickitTeamBundle/Resources/config/routing/api.yml"
    prefix: /api/teams

templates:
    resource: "@TickitTeamBundle/Resources/config/routing/templates.yml"
    prefix: /templates/teams

cosmetic:
    resource: "@TickitTeamBundle/Resources/config/routing/cosmetic.yml"

########################################

team_create:
    pattern: /teams/create
    defaults: { _controller: TickitTeamBundle:Team:create }
    requirements:
        _method: POST

team_edit:
    pattern: /teams/edit/{id}
    defaults: { _controller: TickitTeamBundle:Team:edit }
    requirements:
        _method: POST
        id: \d+

team_delete:
    pattern: /delete/{id}
    defaults: { _controller: TickitTeamBundle:Team:delete }
    requirements:
        id: \d+
