team_index:
  pattern: /{page}
  defaults: { _controller: TickitTeamBundle:Team:index, page: 1 }
  requirements:
    page: \d+
  options:
    expose: true

team_edit:
    pattern: /edit/{id}
    defaults: { _controller: TickitTeamBundle:Team:edit }
    requirements:
        id: \d+

team_delete:
    pattern: /delete/{id}
    defaults: { _controller: TickitTeamBundle:Team:delete }
    requirements:
        id: \d+
