team_edit:
  pattern: /{id}/edit
  defaults: { _controller: TickitTeamBundle:Team:edit }
  requirements:
    _method: GET

team_update:
  pattern: /{id}/update
  defaults: { _controller: TickitTeamBundle:Team:update }
  requirements:
    _method: POST

team_new:
  pattern: /new
  defaults: { _controller: TickitTeamBundle:Team:new }
  requirements:
      _method: GET

team_create:
  pattern: /create
  defaults: { _controller: TickitTeamBundle:Team:create }
  requirements:
    _method: POST

team_index:
  pattern: /{page}
  defaults: { _controller: TickitTeamBundle:Team:index, page: 1 }
  requirements:
    page: \d+
  options:
    expose: true
