Tickit\TeamBundle\Entity\Team:
    properties:
        name:
            - Length: { max: 100, maxMessage: "Name is too long, try something a little shorter (120 characters max)" }
            - NotBlank: { message: "You didn't provide a name, did you forget?" }
