preference_index:
    path: /list/{page}
    defaults: { _controller: tickit_preference.controller.api:listAction, page: 1 }
    methods: [GET]
    requirements:
        page: \d+
    options:
        expose: true
