cosmetic:
    resource: "@TickitClientBundle/Resources/config/routing/cosmetic.yml"

api:
    resource: "@TickitClientBundle/Resources/config/routing/api.yml"
    prefix: /api/clients

templates:
    resource: "@TickitClientBundle/Resources/config/routing/templates.yml"
    prefix: /templates/clients