Tickit\ClientBundle\Entity\Client:
    properties:
        name:
            - Length: { max: 120, maxMessage: "Name is too long, try something a little shorter (120 characters max)" }
            - NotBlank: { message: "You didn't provide a name, did you forget?" }
        url:
            - Url: { message: "Oops, looks like your URL isn't valid." }
