api_preference_list:
    pattern: /list/{page}
    defaults: { _controller: tickit_preference.controller.api:listAction, page: 1 }
    requirements:
        page: \d+
    options:
        expose: true
