cosmetic:
    resource: "@TickitProjectBundle/Resources/config/routing/cosmetic.yml"

api:
    resource: "@TickitProjectBundle/Resources/config/routing/api.yml"
    prefix: /api/projects

templates:
    resource: "@TickitProjectBundle/Resources/config/routing/templates.yml"
    prefix: /templates/projects

###################################

project_create:
    path: /projects/create
    defaults: { _controller: tickit_project.controller.project:createAction }
    methods: [POST]

project_edit:
    path: /projects/edit/{id}
    defaults: { _controller: tickit_project.controller.project:editAction }
    methods: [POST]
    requirements:
        id: \d+

project_delete:
    path: /projects/delete/{id}
    defaults: { _controller: tickit_project.controller.project:deleteAction }
    methods: [DELETE]
    requirements:
        id: \d+
    options:
        expose: true

project_attribute_create:
    path: /projects/attributes/{type}/create
    defaults: { _controller: tickit_project.controller.attribute:createAction }
    methods: [POST]
    requirements:
        type: \w{6,7}

project_attribute_edit:
    path: /projects/attributes/edit/{id}
    defaults: { _controller: tickit_project.controller.attribute:editAction }
    methods: [POST]
    requirements:
        id: \d+

project_attribute_delete:
    path: /projects/attributes/delete/{id}
    defaults: { _controller: tickit_project.controller.attribute:deleteAction }
    methods: [POST]
    requirements:
        id: \d+
