api_project_list:
    pattern: /list/{page}
    defaults: { _controller: TickitProjectBundle:Api:list, page: 1 }
    requirements:
        page: \d+
    options:
        expose: true

api_project_attribute_list:
    pattern: /attributes/list/{page}
    defaults: { _controller: TickitProjectBundle:Api:attributesList, page: 1 }
    requirements:
        page: \d+
    options:
        expose: true
