project_index:
    pattern: /projects/{page}
    defaults: { _controller: TickitCoreBundle:Default:default, page: 1 }
    requirements:
        page: \d+
    options:
        expose: true

project_attribute_index:
    pattern: /attributes/{page}
    defaults: { _controller: TickitProjectBundle:Default:default, page: 1 }
    requirements:
        page: \d+
    options:
        expose: true
