project_index:
    pattern: /projects/{page}
    defaults: { _controller: TickitCoreBundle:Default:default, page: 1 }
    requirements:
        page: \d+
    options:
        expose: true

project_create_view:
    pattern: /projects/create
    defaults: { _controller: TickitCoreBundle:Default:default }
    requirements:
        _method: get
    options:
        expose: true

project_edit_view:
    pattern: /projects/edit/{id}
    defaults: { _controller: TickitCoreBundle:Default:default }
    requirements:
        id: \d+
        _method: get
    options:
        expose: true

project_attribute_index:
    pattern: /attributes/{page}
    defaults: { _controller: TickitProjectBundle:Default:default, page: 1 }
    requirements:
        page: \d+
    options:
        expose: true
